name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GH_PAT }}
          exclude_types: other,chore,build

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}

  build-mac:
    runs-on: macos-latest
    environment: build

    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build for MacOS
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          EP_PRE_RELEASE: true
        run: ./cmd electron build-mac

  build-win:
    runs-on: windows-latest
    environment: build

    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Prepare for Windows Build
        shell: powershell
        run: |
          npm install
          cd electron
          npm install
          cd ../

      - name: Build for Windows
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          EP_PRE_RELEASE: true
        run: |
          mkdir -p ./electron/public
          cp ./electron/index.html ./electron/public/index.html
          node ./electron/build.js build-win

